name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: humble

    - name: Run Tests
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: rosci
        target-ros2-distro: humble

    # - name: Upload Logs
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: colcon-logs
    #     path: ros_ws/log
    #   if: always()