name: clang-format

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.head_ref}}

    - name: Install tools
      run: |
        sudo apt update
        sudo apt install clang-format
    
    - name: Apply formatter
      run: |
        clang-format -i $(find ./src/ -name "*.h" -or -name "*.hpp" -or -name "*.c" -or -name "*.cpp")
        clang-format -i $(find ./include/ -name "*.h" -or -name "*.hpp" -or -name "*.c" -or -name "*.cpp")

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ":art: Apply clang-format"