name: ROSCI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@0.4.1
    with:
      required-ros-distributions: humble

    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.2.7
      with:
        package-name: rosci

    - name: Upload Logs
      uses: actions/upload-artifact@v3.1.1
